version: '3.8'

services:
  web:
    # Building the image using the Dockerfile in the current directory
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=core/server.py
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app